# Generated by Django 4.0.2 on 2022-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fullName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
